// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package bybit

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5a230715DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersClientsTypesBybit(in *jlexer.Lexer, out *OrderBookResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "result":
			easyjson5a230715Decode(in, &out.Result)
		case "retCode":
			out.Code = int(in.Int())
		case "retMsg":
			out.Msg = string(in.String())
		case "retExtInfo":
			easyjson5a230715Decode1(in, &out.Info)
		case "time":
			out.Time = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5a230715EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersClientsTypesBybit(out *jwriter.Writer, in OrderBookResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		easyjson5a230715Encode(out, in.Result)
	}
	{
		const prefix string = ",\"retCode\":"
		out.RawString(prefix)
		out.Int(int(in.Code))
	}
	{
		const prefix string = ",\"retMsg\":"
		out.RawString(prefix)
		out.String(string(in.Msg))
	}
	{
		const prefix string = ",\"retExtInfo\":"
		out.RawString(prefix)
		easyjson5a230715Encode1(out, in.Info)
	}
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix)
		out.Int64(int64(in.Time))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OrderBookResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5a230715EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersClientsTypesBybit(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OrderBookResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5a230715EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersClientsTypesBybit(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OrderBookResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5a230715DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersClientsTypesBybit(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OrderBookResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5a230715DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersClientsTypesBybit(l, v)
}
func easyjson5a230715Decode1(in *jlexer.Lexer, out *struct{}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5a230715Encode1(out *jwriter.Writer, in struct{}) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}
func easyjson5a230715Decode(in *jlexer.Lexer, out *struct {
	S   string     `json:"s"`
	B   [][]string `json:"b"`
	A   [][]string `json:"a"`
	TS  int64      `json:"ts"`
	U   int        `json:"u"`
	Seq int64      `json:"seq"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "s":
			out.S = string(in.String())
		case "b":
			if in.IsNull() {
				in.Skip()
				out.B = nil
			} else {
				in.Delim('[')
				if out.B == nil {
					if !in.IsDelim(']') {
						out.B = make([][]string, 0, 2)
					} else {
						out.B = [][]string{}
					}
				} else {
					out.B = (out.B)[:0]
				}
				for !in.IsDelim(']') {
					var v1 []string
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						in.Delim('[')
						if v1 == nil {
							if !in.IsDelim(']') {
								v1 = make([]string, 0, 4)
							} else {
								v1 = []string{}
							}
						} else {
							v1 = (v1)[:0]
						}
						for !in.IsDelim(']') {
							var v2 string
							v2 = string(in.String())
							v1 = append(v1, v2)
							in.WantComma()
						}
						in.Delim(']')
					}
					out.B = append(out.B, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "a":
			if in.IsNull() {
				in.Skip()
				out.A = nil
			} else {
				in.Delim('[')
				if out.A == nil {
					if !in.IsDelim(']') {
						out.A = make([][]string, 0, 2)
					} else {
						out.A = [][]string{}
					}
				} else {
					out.A = (out.A)[:0]
				}
				for !in.IsDelim(']') {
					var v3 []string
					if in.IsNull() {
						in.Skip()
						v3 = nil
					} else {
						in.Delim('[')
						if v3 == nil {
							if !in.IsDelim(']') {
								v3 = make([]string, 0, 4)
							} else {
								v3 = []string{}
							}
						} else {
							v3 = (v3)[:0]
						}
						for !in.IsDelim(']') {
							var v4 string
							v4 = string(in.String())
							v3 = append(v3, v4)
							in.WantComma()
						}
						in.Delim(']')
					}
					out.A = append(out.A, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "ts":
			out.TS = int64(in.Int64())
		case "u":
			out.U = int(in.Int())
		case "seq":
			out.Seq = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5a230715Encode(out *jwriter.Writer, in struct {
	S   string     `json:"s"`
	B   [][]string `json:"b"`
	A   [][]string `json:"a"`
	TS  int64      `json:"ts"`
	U   int        `json:"u"`
	Seq int64      `json:"seq"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"s\":"
		out.RawString(prefix[1:])
		out.String(string(in.S))
	}
	{
		const prefix string = ",\"b\":"
		out.RawString(prefix)
		if in.B == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.B {
				if v5 > 0 {
					out.RawByte(',')
				}
				if v6 == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v7, v8 := range v6 {
						if v7 > 0 {
							out.RawByte(',')
						}
						out.String(string(v8))
					}
					out.RawByte(']')
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"a\":"
		out.RawString(prefix)
		if in.A == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.A {
				if v9 > 0 {
					out.RawByte(',')
				}
				if v10 == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v11, v12 := range v10 {
						if v11 > 0 {
							out.RawByte(',')
						}
						out.String(string(v12))
					}
					out.RawByte(']')
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"ts\":"
		out.RawString(prefix)
		out.Int64(int64(in.TS))
	}
	{
		const prefix string = ",\"u\":"
		out.RawString(prefix)
		out.Int(int(in.U))
	}
	{
		const prefix string = ",\"seq\":"
		out.RawString(prefix)
		out.Int64(int64(in.Seq))
	}
	out.RawByte('}')
}
func easyjson5a230715DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersClientsTypesBybit1(in *jlexer.Lexer, out *OrderBookRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Category":
			out.Category = InstrumentType(in.String())
		case "Symbol":
			out.Symbol = string(in.String())
		case "Limit":
			out.Limit = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5a230715EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersClientsTypesBybit1(out *jwriter.Writer, in OrderBookRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Category\":"
		out.RawString(prefix[1:])
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"Symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"Limit\":"
		out.RawString(prefix)
		out.Int(int(in.Limit))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OrderBookRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5a230715EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersClientsTypesBybit1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OrderBookRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5a230715EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersClientsTypesBybit1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OrderBookRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5a230715DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersClientsTypesBybit1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OrderBookRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5a230715DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersClientsTypesBybit1(l, v)
}
