// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: instrument_details.sql

package queries

import (
	"context"
)

const SelectAllInstrumentDetails = `-- name: SelectAllInstrumentDetails :many
SELECT exchange, local_symbol, exchange_symbol, price_precision, size_precision, min_lot, created_at, updated_at, deleted_at
FROM quant.instrument_details
WHERE deleted_at IS NULL
`

func (q *Queries) SelectAllInstrumentDetails(ctx context.Context) ([]QuantInstrumentDetail, error) {
	rows, err := q.db.Query(ctx, SelectAllInstrumentDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuantInstrumentDetail
	for rows.Next() {
		var i QuantInstrumentDetail
		if err := rows.Scan(
			&i.Exchange,
			&i.LocalSymbol,
			&i.ExchangeSymbol,
			&i.PricePrecision,
			&i.SizePrecision,
			&i.MinLot,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
