// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
	"database/sql"
	"time"

	"github.com/shopspring/decimal"
)

type QuantInstrumentDetail struct {
	Exchange       string
	LocalSymbol    string
	ExchangeSymbol string
	PricePrecision int32
	SizePrecision  int32
	MinLot         decimal.Decimal
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}

type QuantNameResolver struct {
	Exchange       string
	LocalSymbol    string
	ExchangeSymbol string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}
