// Code generated by mockery v2.40.3. DO NOT EDIT.

package mocks

import (
	context "context"

	sarama "github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// ConsumerGroupSession is an autogenerated mock type for the ConsumerGroupSession type
type ConsumerGroupSession struct {
	mock.Mock
}

type ConsumerGroupSession_Expecter struct {
	mock *mock.Mock
}

func (_m *ConsumerGroupSession) EXPECT() *ConsumerGroupSession_Expecter {
	return &ConsumerGroupSession_Expecter{mock: &_m.Mock}
}

// Claims provides a mock function with given fields:
func (_m *ConsumerGroupSession) Claims() map[string][]int32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Claims")
	}

	var r0 map[string][]int32
	if rf, ok := ret.Get(0).(func() map[string][]int32); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]int32)
		}
	}

	return r0
}

// ConsumerGroupSession_Claims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Claims'
type ConsumerGroupSession_Claims_Call struct {
	*mock.Call
}

// Claims is a helper method to define mock.On call
func (_e *ConsumerGroupSession_Expecter) Claims() *ConsumerGroupSession_Claims_Call {
	return &ConsumerGroupSession_Claims_Call{Call: _e.mock.On("Claims")}
}

func (_c *ConsumerGroupSession_Claims_Call) Run(run func()) *ConsumerGroupSession_Claims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConsumerGroupSession_Claims_Call) Return(_a0 map[string][]int32) *ConsumerGroupSession_Claims_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsumerGroupSession_Claims_Call) RunAndReturn(run func() map[string][]int32) *ConsumerGroupSession_Claims_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function with given fields:
func (_m *ConsumerGroupSession) Commit() {
	_m.Called()
}

// ConsumerGroupSession_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type ConsumerGroupSession_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *ConsumerGroupSession_Expecter) Commit() *ConsumerGroupSession_Commit_Call {
	return &ConsumerGroupSession_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *ConsumerGroupSession_Commit_Call) Run(run func()) *ConsumerGroupSession_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConsumerGroupSession_Commit_Call) Return() *ConsumerGroupSession_Commit_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConsumerGroupSession_Commit_Call) RunAndReturn(run func()) *ConsumerGroupSession_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function with given fields:
func (_m *ConsumerGroupSession) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// ConsumerGroupSession_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type ConsumerGroupSession_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *ConsumerGroupSession_Expecter) Context() *ConsumerGroupSession_Context_Call {
	return &ConsumerGroupSession_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *ConsumerGroupSession_Context_Call) Run(run func()) *ConsumerGroupSession_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConsumerGroupSession_Context_Call) Return(_a0 context.Context) *ConsumerGroupSession_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsumerGroupSession_Context_Call) RunAndReturn(run func() context.Context) *ConsumerGroupSession_Context_Call {
	_c.Call.Return(run)
	return _c
}

// GenerationID provides a mock function with given fields:
func (_m *ConsumerGroupSession) GenerationID() int32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerationID")
	}

	var r0 int32
	if rf, ok := ret.Get(0).(func() int32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int32)
	}

	return r0
}

// ConsumerGroupSession_GenerationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerationID'
type ConsumerGroupSession_GenerationID_Call struct {
	*mock.Call
}

// GenerationID is a helper method to define mock.On call
func (_e *ConsumerGroupSession_Expecter) GenerationID() *ConsumerGroupSession_GenerationID_Call {
	return &ConsumerGroupSession_GenerationID_Call{Call: _e.mock.On("GenerationID")}
}

func (_c *ConsumerGroupSession_GenerationID_Call) Run(run func()) *ConsumerGroupSession_GenerationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConsumerGroupSession_GenerationID_Call) Return(_a0 int32) *ConsumerGroupSession_GenerationID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsumerGroupSession_GenerationID_Call) RunAndReturn(run func() int32) *ConsumerGroupSession_GenerationID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkMessage provides a mock function with given fields: msg, metadata
func (_m *ConsumerGroupSession) MarkMessage(msg *sarama.ConsumerMessage, metadata string) {
	_m.Called(msg, metadata)
}

// ConsumerGroupSession_MarkMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkMessage'
type ConsumerGroupSession_MarkMessage_Call struct {
	*mock.Call
}

// MarkMessage is a helper method to define mock.On call
//   - msg *sarama.ConsumerMessage
//   - metadata string
func (_e *ConsumerGroupSession_Expecter) MarkMessage(msg interface{}, metadata interface{}) *ConsumerGroupSession_MarkMessage_Call {
	return &ConsumerGroupSession_MarkMessage_Call{Call: _e.mock.On("MarkMessage", msg, metadata)}
}

func (_c *ConsumerGroupSession_MarkMessage_Call) Run(run func(msg *sarama.ConsumerMessage, metadata string)) *ConsumerGroupSession_MarkMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*sarama.ConsumerMessage), args[1].(string))
	})
	return _c
}

func (_c *ConsumerGroupSession_MarkMessage_Call) Return() *ConsumerGroupSession_MarkMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConsumerGroupSession_MarkMessage_Call) RunAndReturn(run func(*sarama.ConsumerMessage, string)) *ConsumerGroupSession_MarkMessage_Call {
	_c.Call.Return(run)
	return _c
}

// MarkOffset provides a mock function with given fields: topic, partition, offset, metadata
func (_m *ConsumerGroupSession) MarkOffset(topic string, partition int32, offset int64, metadata string) {
	_m.Called(topic, partition, offset, metadata)
}

// ConsumerGroupSession_MarkOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkOffset'
type ConsumerGroupSession_MarkOffset_Call struct {
	*mock.Call
}

// MarkOffset is a helper method to define mock.On call
//   - topic string
//   - partition int32
//   - offset int64
//   - metadata string
func (_e *ConsumerGroupSession_Expecter) MarkOffset(topic interface{}, partition interface{}, offset interface{}, metadata interface{}) *ConsumerGroupSession_MarkOffset_Call {
	return &ConsumerGroupSession_MarkOffset_Call{Call: _e.mock.On("MarkOffset", topic, partition, offset, metadata)}
}

func (_c *ConsumerGroupSession_MarkOffset_Call) Run(run func(topic string, partition int32, offset int64, metadata string)) *ConsumerGroupSession_MarkOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int32), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *ConsumerGroupSession_MarkOffset_Call) Return() *ConsumerGroupSession_MarkOffset_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConsumerGroupSession_MarkOffset_Call) RunAndReturn(run func(string, int32, int64, string)) *ConsumerGroupSession_MarkOffset_Call {
	_c.Call.Return(run)
	return _c
}

// MemberID provides a mock function with given fields:
func (_m *ConsumerGroupSession) MemberID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MemberID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ConsumerGroupSession_MemberID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MemberID'
type ConsumerGroupSession_MemberID_Call struct {
	*mock.Call
}

// MemberID is a helper method to define mock.On call
func (_e *ConsumerGroupSession_Expecter) MemberID() *ConsumerGroupSession_MemberID_Call {
	return &ConsumerGroupSession_MemberID_Call{Call: _e.mock.On("MemberID")}
}

func (_c *ConsumerGroupSession_MemberID_Call) Run(run func()) *ConsumerGroupSession_MemberID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConsumerGroupSession_MemberID_Call) Return(_a0 string) *ConsumerGroupSession_MemberID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsumerGroupSession_MemberID_Call) RunAndReturn(run func() string) *ConsumerGroupSession_MemberID_Call {
	_c.Call.Return(run)
	return _c
}

// ResetOffset provides a mock function with given fields: topic, partition, offset, metadata
func (_m *ConsumerGroupSession) ResetOffset(topic string, partition int32, offset int64, metadata string) {
	_m.Called(topic, partition, offset, metadata)
}

// ConsumerGroupSession_ResetOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetOffset'
type ConsumerGroupSession_ResetOffset_Call struct {
	*mock.Call
}

// ResetOffset is a helper method to define mock.On call
//   - topic string
//   - partition int32
//   - offset int64
//   - metadata string
func (_e *ConsumerGroupSession_Expecter) ResetOffset(topic interface{}, partition interface{}, offset interface{}, metadata interface{}) *ConsumerGroupSession_ResetOffset_Call {
	return &ConsumerGroupSession_ResetOffset_Call{Call: _e.mock.On("ResetOffset", topic, partition, offset, metadata)}
}

func (_c *ConsumerGroupSession_ResetOffset_Call) Run(run func(topic string, partition int32, offset int64, metadata string)) *ConsumerGroupSession_ResetOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int32), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *ConsumerGroupSession_ResetOffset_Call) Return() *ConsumerGroupSession_ResetOffset_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConsumerGroupSession_ResetOffset_Call) RunAndReturn(run func(string, int32, int64, string)) *ConsumerGroupSession_ResetOffset_Call {
	_c.Call.Return(run)
	return _c
}

// NewConsumerGroupSession creates a new instance of ConsumerGroupSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumerGroupSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsumerGroupSession {
	mock := &ConsumerGroupSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
