package f

const (
	Module                           = "module"
	Message                          = "message"
	MessageType                      = "message_type"
	Method                           = "method"
	Path                             = "path"
	MDResponse                       = "md_response"
	MDRequest                        = "md_request"
	URL                              = "url"
	BinanceError                     = "binance_error"
	APIClient                        = "api_client"
	OKXError                         = "okx_error"
	BybitError                       = "bybit_error"
	FineryMarketsError               = "finery_markets_error"
	KrakenError                      = "kraken_error"
	OKXUserStreamSubscribeResponse   = "okx_user_stream_subscribe_response"
	OKXLoginResponse                 = "okx_login_response"
	BybitUserStreamSubscribeResponse = "bybit_user_stream_subscribe_response"
	BybitAuthResponse                = "bybit_auth_response"
	BybitHeartbeatResponse           = "bybit_heartbeat_response"
	OrderUpdate                      = "order_update"
	UserStreamPositionsResponse      = "user_stream_positions_response"
	UserStreamBalanceResponse        = "user_stream_balance_response"
	AmendOrder                       = "amend_order"
	UserStreamOrderResponse          = "user_stream_order_response"
	CreateOrderFailed                = "create_order_failed"
	CancelOrderFailed                = "cancel_order_failed"
	ModifyOrderFailed                = "modify_order_failed"
	OrderCanceled                    = "order_canceled"
	CancelOrderRequest               = "cancel_order_request"
	OrderCreatedAck                  = "order_created_ack"
	OrderMoveAck                     = "order_move_ack"
	OrderCreateRequest               = "order_create_request"
	OrderMoveRequest                 = "order_move_request"
	OrderMovedResponse               = "order_move_response"
	Instrument                       = "instrument"
	InstrumentDetails                = "instrument_details"
	SubscribeInstruments             = "subscribe_instruments"
	ExchangeClientOrderID            = "exchange_client_order_id"
	PistonID                         = "Piston_id"
	PistonTradingMessage             = "Piston_trading_message"
	PistonTradingMessageType         = "Piston_trading_message_type"
	RateLimit                        = "rate_limit"
	ListenKey                        = "listen_key"
	SystemStatus                     = "system_status"
)
