// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package okx

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx(in *jlexer.Lexer, out *SubscriptionMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "op":
			out.Op = EventType(in.String())
		case "args":
			if in.IsNull() {
				in.Skip()
				out.Args = nil
			} else {
				in.Delim('[')
				if out.Args == nil {
					if !in.IsDelim(']') {
						out.Args = make([]SubscriptionArgs, 0, 2)
					} else {
						out.Args = []SubscriptionArgs{}
					}
				} else {
					out.Args = (out.Args)[:0]
				}
				for !in.IsDelim(']') {
					var v1 SubscriptionArgs
					(v1).UnmarshalEasyJSON(in)
					out.Args = append(out.Args, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx(out *jwriter.Writer, in SubscriptionMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"op\":"
		out.RawString(prefix[1:])
		out.String(string(in.Op))
	}
	{
		const prefix string = ",\"args\":"
		out.RawString(prefix)
		if in.Args == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Args {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SubscriptionMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SubscriptionMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SubscriptionMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SubscriptionMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx(l, v)
}
func easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx1(in *jlexer.Lexer, out *SubscriptionArgs) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "channel":
			out.Channel = string(in.String())
		case "instType":
			out.InstType = InstrumentType(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx1(out *jwriter.Writer, in SubscriptionArgs) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"channel\":"
		out.RawString(prefix[1:])
		out.String(string(in.Channel))
	}
	{
		const prefix string = ",\"instType\":"
		out.RawString(prefix)
		out.String(string(in.InstType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SubscriptionArgs) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SubscriptionArgs) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SubscriptionArgs) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SubscriptionArgs) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx1(l, v)
}
func easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx2(in *jlexer.Lexer, out *SubscribeResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "event":
			out.Event = EventType(in.String())
		case "code":
			out.Code = string(in.String())
		case "msg":
			out.Msg = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx2(out *jwriter.Writer, in SubscribeResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"event\":"
		out.RawString(prefix[1:])
		out.String(string(in.Event))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"msg\":"
		out.RawString(prefix)
		out.String(string(in.Msg))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SubscribeResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SubscribeResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SubscribeResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SubscribeResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx2(l, v)
}
func easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx3(in *jlexer.Lexer, out *OrderUpdate) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "arg":
			easyjson9d6b4be7Decode(in, &out.Arg)
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]struct {
							AccFillSz         string `json:"accFillSz"`
							AlgoClOrdID       string `json:"algoClOrdId"`
							AlgoID            string `json:"algoId"`
							AmendResult       string `json:"amendResult"`
							AmendSource       string `json:"amendSource"`
							AttachAlgoClOrdID string `json:"attachAlgoClOrdId"`
							AvgPx             string `json:"avgPx"`
							CTime             string `json:"cTime"`
							CancelSource      string `json:"cancelSource"`
							Category          string `json:"category"`
							Ccy               string `json:"ccy"`
							ClOrdID           string `json:"clOrdId"`
							Code              string `json:"code"`
							ExecType          string `json:"execType"`
							Fee               string `json:"fee"`
							FeeCcy            string `json:"feeCcy"`
							FillFee           string `json:"fillFee"`
							FillFeeCcy        string `json:"fillFeeCcy"`
							FillFwdPx         string `json:"fillFwdPx"`
							FillMarkPx        string `json:"fillMarkPx"`
							FillMarkVol       string `json:"fillMarkVol"`
							FillNotionalUsd   string `json:"fillNotionalUsd"`
							FillPnl           string `json:"fillPnl"`
							FillPx            string `json:"fillPx"`
							FillPxUsd         string `json:"fillPxUsd"`
							FillPxVol         string `json:"fillPxVol"`
							FillSz            string `json:"fillSz"`
							FillTime          string `json:"fillTime"`
							InstID            string `json:"instId"`
							InstType          string `json:"instType"`
							Lever             string `json:"lever"`
							Msg               string `json:"msg"`
							NotionalUsd       string `json:"notionalUsd"`
							OrdID             string `json:"ordId"`
							OrdType           string `json:"ordType"`
							Pnl               string `json:"pnl"`
							PosSide           string `json:"posSide"`
							Px                string `json:"px"`
							PxType            string `json:"pxType"`
							PxUsd             string `json:"pxUsd"`
							PxVol             string `json:"pxVol"`
							QuickMgnType      string `json:"quickMgnType"`
							Rebate            string `json:"rebate"`
							RebateCcy         string `json:"rebateCcy"`
							ReduceOnly        string `json:"reduceOnly"`
							ReqID             string `json:"reqId"`
							Side              string `json:"side"`
							SlOrdPx           string `json:"slOrdPx"`
							SlTriggerPx       string `json:"slTriggerPx"`
							SlTriggerPxType   string `json:"slTriggerPxType"`
							Source            string `json:"source"`
							State             string `json:"state"`
							StpID             string `json:"stpId"`
							StpMode           string `json:"stpMode"`
							Sz                string `json:"sz"`
							Tag               string `json:"tag"`
							TdMode            string `json:"tdMode"`
							TgtCcy            string `json:"tgtCcy"`
							TpOrdPx           string `json:"tpOrdPx"`
							TpTriggerPx       string `json:"tpTriggerPx"`
							TpTriggerPxType   string `json:"tpTriggerPxType"`
							TradeID           string `json:"tradeId"`
							UTime             string `json:"uTime"`
						}, 0, 0)
					} else {
						out.Data = []struct {
							AccFillSz         string `json:"accFillSz"`
							AlgoClOrdID       string `json:"algoClOrdId"`
							AlgoID            string `json:"algoId"`
							AmendResult       string `json:"amendResult"`
							AmendSource       string `json:"amendSource"`
							AttachAlgoClOrdID string `json:"attachAlgoClOrdId"`
							AvgPx             string `json:"avgPx"`
							CTime             string `json:"cTime"`
							CancelSource      string `json:"cancelSource"`
							Category          string `json:"category"`
							Ccy               string `json:"ccy"`
							ClOrdID           string `json:"clOrdId"`
							Code              string `json:"code"`
							ExecType          string `json:"execType"`
							Fee               string `json:"fee"`
							FeeCcy            string `json:"feeCcy"`
							FillFee           string `json:"fillFee"`
							FillFeeCcy        string `json:"fillFeeCcy"`
							FillFwdPx         string `json:"fillFwdPx"`
							FillMarkPx        string `json:"fillMarkPx"`
							FillMarkVol       string `json:"fillMarkVol"`
							FillNotionalUsd   string `json:"fillNotionalUsd"`
							FillPnl           string `json:"fillPnl"`
							FillPx            string `json:"fillPx"`
							FillPxUsd         string `json:"fillPxUsd"`
							FillPxVol         string `json:"fillPxVol"`
							FillSz            string `json:"fillSz"`
							FillTime          string `json:"fillTime"`
							InstID            string `json:"instId"`
							InstType          string `json:"instType"`
							Lever             string `json:"lever"`
							Msg               string `json:"msg"`
							NotionalUsd       string `json:"notionalUsd"`
							OrdID             string `json:"ordId"`
							OrdType           string `json:"ordType"`
							Pnl               string `json:"pnl"`
							PosSide           string `json:"posSide"`
							Px                string `json:"px"`
							PxType            string `json:"pxType"`
							PxUsd             string `json:"pxUsd"`
							PxVol             string `json:"pxVol"`
							QuickMgnType      string `json:"quickMgnType"`
							Rebate            string `json:"rebate"`
							RebateCcy         string `json:"rebateCcy"`
							ReduceOnly        string `json:"reduceOnly"`
							ReqID             string `json:"reqId"`
							Side              string `json:"side"`
							SlOrdPx           string `json:"slOrdPx"`
							SlTriggerPx       string `json:"slTriggerPx"`
							SlTriggerPxType   string `json:"slTriggerPxType"`
							Source            string `json:"source"`
							State             string `json:"state"`
							StpID             string `json:"stpId"`
							StpMode           string `json:"stpMode"`
							Sz                string `json:"sz"`
							Tag               string `json:"tag"`
							TdMode            string `json:"tdMode"`
							TgtCcy            string `json:"tgtCcy"`
							TpOrdPx           string `json:"tpOrdPx"`
							TpTriggerPx       string `json:"tpTriggerPx"`
							TpTriggerPxType   string `json:"tpTriggerPxType"`
							TradeID           string `json:"tradeId"`
							UTime             string `json:"uTime"`
						}{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v4 struct {
						AccFillSz         string `json:"accFillSz"`
						AlgoClOrdID       string `json:"algoClOrdId"`
						AlgoID            string `json:"algoId"`
						AmendResult       string `json:"amendResult"`
						AmendSource       string `json:"amendSource"`
						AttachAlgoClOrdID string `json:"attachAlgoClOrdId"`
						AvgPx             string `json:"avgPx"`
						CTime             string `json:"cTime"`
						CancelSource      string `json:"cancelSource"`
						Category          string `json:"category"`
						Ccy               string `json:"ccy"`
						ClOrdID           string `json:"clOrdId"`
						Code              string `json:"code"`
						ExecType          string `json:"execType"`
						Fee               string `json:"fee"`
						FeeCcy            string `json:"feeCcy"`
						FillFee           string `json:"fillFee"`
						FillFeeCcy        string `json:"fillFeeCcy"`
						FillFwdPx         string `json:"fillFwdPx"`
						FillMarkPx        string `json:"fillMarkPx"`
						FillMarkVol       string `json:"fillMarkVol"`
						FillNotionalUsd   string `json:"fillNotionalUsd"`
						FillPnl           string `json:"fillPnl"`
						FillPx            string `json:"fillPx"`
						FillPxUsd         string `json:"fillPxUsd"`
						FillPxVol         string `json:"fillPxVol"`
						FillSz            string `json:"fillSz"`
						FillTime          string `json:"fillTime"`
						InstID            string `json:"instId"`
						InstType          string `json:"instType"`
						Lever             string `json:"lever"`
						Msg               string `json:"msg"`
						NotionalUsd       string `json:"notionalUsd"`
						OrdID             string `json:"ordId"`
						OrdType           string `json:"ordType"`
						Pnl               string `json:"pnl"`
						PosSide           string `json:"posSide"`
						Px                string `json:"px"`
						PxType            string `json:"pxType"`
						PxUsd             string `json:"pxUsd"`
						PxVol             string `json:"pxVol"`
						QuickMgnType      string `json:"quickMgnType"`
						Rebate            string `json:"rebate"`
						RebateCcy         string `json:"rebateCcy"`
						ReduceOnly        string `json:"reduceOnly"`
						ReqID             string `json:"reqId"`
						Side              string `json:"side"`
						SlOrdPx           string `json:"slOrdPx"`
						SlTriggerPx       string `json:"slTriggerPx"`
						SlTriggerPxType   string `json:"slTriggerPxType"`
						Source            string `json:"source"`
						State             string `json:"state"`
						StpID             string `json:"stpId"`
						StpMode           string `json:"stpMode"`
						Sz                string `json:"sz"`
						Tag               string `json:"tag"`
						TdMode            string `json:"tdMode"`
						TgtCcy            string `json:"tgtCcy"`
						TpOrdPx           string `json:"tpOrdPx"`
						TpTriggerPx       string `json:"tpTriggerPx"`
						TpTriggerPxType   string `json:"tpTriggerPxType"`
						TradeID           string `json:"tradeId"`
						UTime             string `json:"uTime"`
					}
					easyjson9d6b4be7Decode1(in, &v4)
					out.Data = append(out.Data, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "event":
			out.Event = EventType(in.String())
		case "code":
			out.Code = string(in.String())
		case "msg":
			out.Msg = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx3(out *jwriter.Writer, in OrderUpdate) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"arg\":"
		out.RawString(prefix[1:])
		easyjson9d6b4be7Encode(out, in.Arg)
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Data {
				if v5 > 0 {
					out.RawByte(',')
				}
				easyjson9d6b4be7Encode1(out, v6)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"event\":"
		out.RawString(prefix)
		out.String(string(in.Event))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"msg\":"
		out.RawString(prefix)
		out.String(string(in.Msg))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OrderUpdate) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OrderUpdate) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OrderUpdate) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OrderUpdate) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx3(l, v)
}
func easyjson9d6b4be7Decode1(in *jlexer.Lexer, out *struct {
	AccFillSz         string `json:"accFillSz"`
	AlgoClOrdID       string `json:"algoClOrdId"`
	AlgoID            string `json:"algoId"`
	AmendResult       string `json:"amendResult"`
	AmendSource       string `json:"amendSource"`
	AttachAlgoClOrdID string `json:"attachAlgoClOrdId"`
	AvgPx             string `json:"avgPx"`
	CTime             string `json:"cTime"`
	CancelSource      string `json:"cancelSource"`
	Category          string `json:"category"`
	Ccy               string `json:"ccy"`
	ClOrdID           string `json:"clOrdId"`
	Code              string `json:"code"`
	ExecType          string `json:"execType"`
	Fee               string `json:"fee"`
	FeeCcy            string `json:"feeCcy"`
	FillFee           string `json:"fillFee"`
	FillFeeCcy        string `json:"fillFeeCcy"`
	FillFwdPx         string `json:"fillFwdPx"`
	FillMarkPx        string `json:"fillMarkPx"`
	FillMarkVol       string `json:"fillMarkVol"`
	FillNotionalUsd   string `json:"fillNotionalUsd"`
	FillPnl           string `json:"fillPnl"`
	FillPx            string `json:"fillPx"`
	FillPxUsd         string `json:"fillPxUsd"`
	FillPxVol         string `json:"fillPxVol"`
	FillSz            string `json:"fillSz"`
	FillTime          string `json:"fillTime"`
	InstID            string `json:"instId"`
	InstType          string `json:"instType"`
	Lever             string `json:"lever"`
	Msg               string `json:"msg"`
	NotionalUsd       string `json:"notionalUsd"`
	OrdID             string `json:"ordId"`
	OrdType           string `json:"ordType"`
	Pnl               string `json:"pnl"`
	PosSide           string `json:"posSide"`
	Px                string `json:"px"`
	PxType            string `json:"pxType"`
	PxUsd             string `json:"pxUsd"`
	PxVol             string `json:"pxVol"`
	QuickMgnType      string `json:"quickMgnType"`
	Rebate            string `json:"rebate"`
	RebateCcy         string `json:"rebateCcy"`
	ReduceOnly        string `json:"reduceOnly"`
	ReqID             string `json:"reqId"`
	Side              string `json:"side"`
	SlOrdPx           string `json:"slOrdPx"`
	SlTriggerPx       string `json:"slTriggerPx"`
	SlTriggerPxType   string `json:"slTriggerPxType"`
	Source            string `json:"source"`
	State             string `json:"state"`
	StpID             string `json:"stpId"`
	StpMode           string `json:"stpMode"`
	Sz                string `json:"sz"`
	Tag               string `json:"tag"`
	TdMode            string `json:"tdMode"`
	TgtCcy            string `json:"tgtCcy"`
	TpOrdPx           string `json:"tpOrdPx"`
	TpTriggerPx       string `json:"tpTriggerPx"`
	TpTriggerPxType   string `json:"tpTriggerPxType"`
	TradeID           string `json:"tradeId"`
	UTime             string `json:"uTime"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "accFillSz":
			out.AccFillSz = string(in.String())
		case "algoClOrdId":
			out.AlgoClOrdID = string(in.String())
		case "algoId":
			out.AlgoID = string(in.String())
		case "amendResult":
			out.AmendResult = string(in.String())
		case "amendSource":
			out.AmendSource = string(in.String())
		case "attachAlgoClOrdId":
			out.AttachAlgoClOrdID = string(in.String())
		case "avgPx":
			out.AvgPx = string(in.String())
		case "cTime":
			out.CTime = string(in.String())
		case "cancelSource":
			out.CancelSource = string(in.String())
		case "category":
			out.Category = string(in.String())
		case "ccy":
			out.Ccy = string(in.String())
		case "clOrdId":
			out.ClOrdID = string(in.String())
		case "code":
			out.Code = string(in.String())
		case "execType":
			out.ExecType = string(in.String())
		case "fee":
			out.Fee = string(in.String())
		case "feeCcy":
			out.FeeCcy = string(in.String())
		case "fillFee":
			out.FillFee = string(in.String())
		case "fillFeeCcy":
			out.FillFeeCcy = string(in.String())
		case "fillFwdPx":
			out.FillFwdPx = string(in.String())
		case "fillMarkPx":
			out.FillMarkPx = string(in.String())
		case "fillMarkVol":
			out.FillMarkVol = string(in.String())
		case "fillNotionalUsd":
			out.FillNotionalUsd = string(in.String())
		case "fillPnl":
			out.FillPnl = string(in.String())
		case "fillPx":
			out.FillPx = string(in.String())
		case "fillPxUsd":
			out.FillPxUsd = string(in.String())
		case "fillPxVol":
			out.FillPxVol = string(in.String())
		case "fillSz":
			out.FillSz = string(in.String())
		case "fillTime":
			out.FillTime = string(in.String())
		case "instId":
			out.InstID = string(in.String())
		case "instType":
			out.InstType = string(in.String())
		case "lever":
			out.Lever = string(in.String())
		case "msg":
			out.Msg = string(in.String())
		case "notionalUsd":
			out.NotionalUsd = string(in.String())
		case "ordId":
			out.OrdID = string(in.String())
		case "ordType":
			out.OrdType = string(in.String())
		case "pnl":
			out.Pnl = string(in.String())
		case "posSide":
			out.PosSide = string(in.String())
		case "px":
			out.Px = string(in.String())
		case "pxType":
			out.PxType = string(in.String())
		case "pxUsd":
			out.PxUsd = string(in.String())
		case "pxVol":
			out.PxVol = string(in.String())
		case "quickMgnType":
			out.QuickMgnType = string(in.String())
		case "rebate":
			out.Rebate = string(in.String())
		case "rebateCcy":
			out.RebateCcy = string(in.String())
		case "reduceOnly":
			out.ReduceOnly = string(in.String())
		case "reqId":
			out.ReqID = string(in.String())
		case "side":
			out.Side = string(in.String())
		case "slOrdPx":
			out.SlOrdPx = string(in.String())
		case "slTriggerPx":
			out.SlTriggerPx = string(in.String())
		case "slTriggerPxType":
			out.SlTriggerPxType = string(in.String())
		case "source":
			out.Source = string(in.String())
		case "state":
			out.State = string(in.String())
		case "stpId":
			out.StpID = string(in.String())
		case "stpMode":
			out.StpMode = string(in.String())
		case "sz":
			out.Sz = string(in.String())
		case "tag":
			out.Tag = string(in.String())
		case "tdMode":
			out.TdMode = string(in.String())
		case "tgtCcy":
			out.TgtCcy = string(in.String())
		case "tpOrdPx":
			out.TpOrdPx = string(in.String())
		case "tpTriggerPx":
			out.TpTriggerPx = string(in.String())
		case "tpTriggerPxType":
			out.TpTriggerPxType = string(in.String())
		case "tradeId":
			out.TradeID = string(in.String())
		case "uTime":
			out.UTime = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9d6b4be7Encode1(out *jwriter.Writer, in struct {
	AccFillSz         string `json:"accFillSz"`
	AlgoClOrdID       string `json:"algoClOrdId"`
	AlgoID            string `json:"algoId"`
	AmendResult       string `json:"amendResult"`
	AmendSource       string `json:"amendSource"`
	AttachAlgoClOrdID string `json:"attachAlgoClOrdId"`
	AvgPx             string `json:"avgPx"`
	CTime             string `json:"cTime"`
	CancelSource      string `json:"cancelSource"`
	Category          string `json:"category"`
	Ccy               string `json:"ccy"`
	ClOrdID           string `json:"clOrdId"`
	Code              string `json:"code"`
	ExecType          string `json:"execType"`
	Fee               string `json:"fee"`
	FeeCcy            string `json:"feeCcy"`
	FillFee           string `json:"fillFee"`
	FillFeeCcy        string `json:"fillFeeCcy"`
	FillFwdPx         string `json:"fillFwdPx"`
	FillMarkPx        string `json:"fillMarkPx"`
	FillMarkVol       string `json:"fillMarkVol"`
	FillNotionalUsd   string `json:"fillNotionalUsd"`
	FillPnl           string `json:"fillPnl"`
	FillPx            string `json:"fillPx"`
	FillPxUsd         string `json:"fillPxUsd"`
	FillPxVol         string `json:"fillPxVol"`
	FillSz            string `json:"fillSz"`
	FillTime          string `json:"fillTime"`
	InstID            string `json:"instId"`
	InstType          string `json:"instType"`
	Lever             string `json:"lever"`
	Msg               string `json:"msg"`
	NotionalUsd       string `json:"notionalUsd"`
	OrdID             string `json:"ordId"`
	OrdType           string `json:"ordType"`
	Pnl               string `json:"pnl"`
	PosSide           string `json:"posSide"`
	Px                string `json:"px"`
	PxType            string `json:"pxType"`
	PxUsd             string `json:"pxUsd"`
	PxVol             string `json:"pxVol"`
	QuickMgnType      string `json:"quickMgnType"`
	Rebate            string `json:"rebate"`
	RebateCcy         string `json:"rebateCcy"`
	ReduceOnly        string `json:"reduceOnly"`
	ReqID             string `json:"reqId"`
	Side              string `json:"side"`
	SlOrdPx           string `json:"slOrdPx"`
	SlTriggerPx       string `json:"slTriggerPx"`
	SlTriggerPxType   string `json:"slTriggerPxType"`
	Source            string `json:"source"`
	State             string `json:"state"`
	StpID             string `json:"stpId"`
	StpMode           string `json:"stpMode"`
	Sz                string `json:"sz"`
	Tag               string `json:"tag"`
	TdMode            string `json:"tdMode"`
	TgtCcy            string `json:"tgtCcy"`
	TpOrdPx           string `json:"tpOrdPx"`
	TpTriggerPx       string `json:"tpTriggerPx"`
	TpTriggerPxType   string `json:"tpTriggerPxType"`
	TradeID           string `json:"tradeId"`
	UTime             string `json:"uTime"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"accFillSz\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccFillSz))
	}
	{
		const prefix string = ",\"algoClOrdId\":"
		out.RawString(prefix)
		out.String(string(in.AlgoClOrdID))
	}
	{
		const prefix string = ",\"algoId\":"
		out.RawString(prefix)
		out.String(string(in.AlgoID))
	}
	{
		const prefix string = ",\"amendResult\":"
		out.RawString(prefix)
		out.String(string(in.AmendResult))
	}
	{
		const prefix string = ",\"amendSource\":"
		out.RawString(prefix)
		out.String(string(in.AmendSource))
	}
	{
		const prefix string = ",\"attachAlgoClOrdId\":"
		out.RawString(prefix)
		out.String(string(in.AttachAlgoClOrdID))
	}
	{
		const prefix string = ",\"avgPx\":"
		out.RawString(prefix)
		out.String(string(in.AvgPx))
	}
	{
		const prefix string = ",\"cTime\":"
		out.RawString(prefix)
		out.String(string(in.CTime))
	}
	{
		const prefix string = ",\"cancelSource\":"
		out.RawString(prefix)
		out.String(string(in.CancelSource))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"ccy\":"
		out.RawString(prefix)
		out.String(string(in.Ccy))
	}
	{
		const prefix string = ",\"clOrdId\":"
		out.RawString(prefix)
		out.String(string(in.ClOrdID))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"execType\":"
		out.RawString(prefix)
		out.String(string(in.ExecType))
	}
	{
		const prefix string = ",\"fee\":"
		out.RawString(prefix)
		out.String(string(in.Fee))
	}
	{
		const prefix string = ",\"feeCcy\":"
		out.RawString(prefix)
		out.String(string(in.FeeCcy))
	}
	{
		const prefix string = ",\"fillFee\":"
		out.RawString(prefix)
		out.String(string(in.FillFee))
	}
	{
		const prefix string = ",\"fillFeeCcy\":"
		out.RawString(prefix)
		out.String(string(in.FillFeeCcy))
	}
	{
		const prefix string = ",\"fillFwdPx\":"
		out.RawString(prefix)
		out.String(string(in.FillFwdPx))
	}
	{
		const prefix string = ",\"fillMarkPx\":"
		out.RawString(prefix)
		out.String(string(in.FillMarkPx))
	}
	{
		const prefix string = ",\"fillMarkVol\":"
		out.RawString(prefix)
		out.String(string(in.FillMarkVol))
	}
	{
		const prefix string = ",\"fillNotionalUsd\":"
		out.RawString(prefix)
		out.String(string(in.FillNotionalUsd))
	}
	{
		const prefix string = ",\"fillPnl\":"
		out.RawString(prefix)
		out.String(string(in.FillPnl))
	}
	{
		const prefix string = ",\"fillPx\":"
		out.RawString(prefix)
		out.String(string(in.FillPx))
	}
	{
		const prefix string = ",\"fillPxUsd\":"
		out.RawString(prefix)
		out.String(string(in.FillPxUsd))
	}
	{
		const prefix string = ",\"fillPxVol\":"
		out.RawString(prefix)
		out.String(string(in.FillPxVol))
	}
	{
		const prefix string = ",\"fillSz\":"
		out.RawString(prefix)
		out.String(string(in.FillSz))
	}
	{
		const prefix string = ",\"fillTime\":"
		out.RawString(prefix)
		out.String(string(in.FillTime))
	}
	{
		const prefix string = ",\"instId\":"
		out.RawString(prefix)
		out.String(string(in.InstID))
	}
	{
		const prefix string = ",\"instType\":"
		out.RawString(prefix)
		out.String(string(in.InstType))
	}
	{
		const prefix string = ",\"lever\":"
		out.RawString(prefix)
		out.String(string(in.Lever))
	}
	{
		const prefix string = ",\"msg\":"
		out.RawString(prefix)
		out.String(string(in.Msg))
	}
	{
		const prefix string = ",\"notionalUsd\":"
		out.RawString(prefix)
		out.String(string(in.NotionalUsd))
	}
	{
		const prefix string = ",\"ordId\":"
		out.RawString(prefix)
		out.String(string(in.OrdID))
	}
	{
		const prefix string = ",\"ordType\":"
		out.RawString(prefix)
		out.String(string(in.OrdType))
	}
	{
		const prefix string = ",\"pnl\":"
		out.RawString(prefix)
		out.String(string(in.Pnl))
	}
	{
		const prefix string = ",\"posSide\":"
		out.RawString(prefix)
		out.String(string(in.PosSide))
	}
	{
		const prefix string = ",\"px\":"
		out.RawString(prefix)
		out.String(string(in.Px))
	}
	{
		const prefix string = ",\"pxType\":"
		out.RawString(prefix)
		out.String(string(in.PxType))
	}
	{
		const prefix string = ",\"pxUsd\":"
		out.RawString(prefix)
		out.String(string(in.PxUsd))
	}
	{
		const prefix string = ",\"pxVol\":"
		out.RawString(prefix)
		out.String(string(in.PxVol))
	}
	{
		const prefix string = ",\"quickMgnType\":"
		out.RawString(prefix)
		out.String(string(in.QuickMgnType))
	}
	{
		const prefix string = ",\"rebate\":"
		out.RawString(prefix)
		out.String(string(in.Rebate))
	}
	{
		const prefix string = ",\"rebateCcy\":"
		out.RawString(prefix)
		out.String(string(in.RebateCcy))
	}
	{
		const prefix string = ",\"reduceOnly\":"
		out.RawString(prefix)
		out.String(string(in.ReduceOnly))
	}
	{
		const prefix string = ",\"reqId\":"
		out.RawString(prefix)
		out.String(string(in.ReqID))
	}
	{
		const prefix string = ",\"side\":"
		out.RawString(prefix)
		out.String(string(in.Side))
	}
	{
		const prefix string = ",\"slOrdPx\":"
		out.RawString(prefix)
		out.String(string(in.SlOrdPx))
	}
	{
		const prefix string = ",\"slTriggerPx\":"
		out.RawString(prefix)
		out.String(string(in.SlTriggerPx))
	}
	{
		const prefix string = ",\"slTriggerPxType\":"
		out.RawString(prefix)
		out.String(string(in.SlTriggerPxType))
	}
	{
		const prefix string = ",\"source\":"
		out.RawString(prefix)
		out.String(string(in.Source))
	}
	{
		const prefix string = ",\"state\":"
		out.RawString(prefix)
		out.String(string(in.State))
	}
	{
		const prefix string = ",\"stpId\":"
		out.RawString(prefix)
		out.String(string(in.StpID))
	}
	{
		const prefix string = ",\"stpMode\":"
		out.RawString(prefix)
		out.String(string(in.StpMode))
	}
	{
		const prefix string = ",\"sz\":"
		out.RawString(prefix)
		out.String(string(in.Sz))
	}
	{
		const prefix string = ",\"tag\":"
		out.RawString(prefix)
		out.String(string(in.Tag))
	}
	{
		const prefix string = ",\"tdMode\":"
		out.RawString(prefix)
		out.String(string(in.TdMode))
	}
	{
		const prefix string = ",\"tgtCcy\":"
		out.RawString(prefix)
		out.String(string(in.TgtCcy))
	}
	{
		const prefix string = ",\"tpOrdPx\":"
		out.RawString(prefix)
		out.String(string(in.TpOrdPx))
	}
	{
		const prefix string = ",\"tpTriggerPx\":"
		out.RawString(prefix)
		out.String(string(in.TpTriggerPx))
	}
	{
		const prefix string = ",\"tpTriggerPxType\":"
		out.RawString(prefix)
		out.String(string(in.TpTriggerPxType))
	}
	{
		const prefix string = ",\"tradeId\":"
		out.RawString(prefix)
		out.String(string(in.TradeID))
	}
	{
		const prefix string = ",\"uTime\":"
		out.RawString(prefix)
		out.String(string(in.UTime))
	}
	out.RawByte('}')
}
func easyjson9d6b4be7Decode(in *jlexer.Lexer, out *struct {
	Channel  string `json:"channel"`
	InstType string `json:"instType"`
	UID      string `json:"uid"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "channel":
			out.Channel = string(in.String())
		case "instType":
			out.InstType = string(in.String())
		case "uid":
			out.UID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9d6b4be7Encode(out *jwriter.Writer, in struct {
	Channel  string `json:"channel"`
	InstType string `json:"instType"`
	UID      string `json:"uid"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"channel\":"
		out.RawString(prefix[1:])
		out.String(string(in.Channel))
	}
	{
		const prefix string = ",\"instType\":"
		out.RawString(prefix)
		out.String(string(in.InstType))
	}
	{
		const prefix string = ",\"uid\":"
		out.RawString(prefix)
		out.String(string(in.UID))
	}
	out.RawByte('}')
}
func easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx4(in *jlexer.Lexer, out *OrderAck) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "op":
			out.Op = EventType(in.String())
		case "event":
			out.Event = EventType(in.String())
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]Data, 0, 0)
					} else {
						out.Data = []Data{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v7 Data
					(v7).UnmarshalEasyJSON(in)
					out.Data = append(out.Data, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "code":
			out.Code = string(in.String())
		case "msg":
			out.Msg = string(in.String())
		case "inTime":
			out.InTime = string(in.String())
		case "outTime":
			out.OutTime = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx4(out *jwriter.Writer, in OrderAck) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"op\":"
		out.RawString(prefix)
		out.String(string(in.Op))
	}
	{
		const prefix string = ",\"event\":"
		out.RawString(prefix)
		out.String(string(in.Event))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Data {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"msg\":"
		out.RawString(prefix)
		out.String(string(in.Msg))
	}
	{
		const prefix string = ",\"inTime\":"
		out.RawString(prefix)
		out.String(string(in.InTime))
	}
	{
		const prefix string = ",\"outTime\":"
		out.RawString(prefix)
		out.String(string(in.OutTime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OrderAck) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OrderAck) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OrderAck) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OrderAck) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx4(l, v)
}
func easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx5(in *jlexer.Lexer, out *ModifyOrder) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "op":
			out.Op = EventType(in.String())
		case "args":
			if in.IsNull() {
				in.Skip()
				out.Args = nil
			} else {
				in.Delim('[')
				if out.Args == nil {
					if !in.IsDelim(']') {
						out.Args = make([]ModifyArgs, 0, 0)
					} else {
						out.Args = []ModifyArgs{}
					}
				} else {
					out.Args = (out.Args)[:0]
				}
				for !in.IsDelim(']') {
					var v10 ModifyArgs
					(v10).UnmarshalEasyJSON(in)
					out.Args = append(out.Args, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx5(out *jwriter.Writer, in ModifyOrder) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"op\":"
		out.RawString(prefix)
		out.String(string(in.Op))
	}
	{
		const prefix string = ",\"args\":"
		out.RawString(prefix)
		if in.Args == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Args {
				if v11 > 0 {
					out.RawByte(',')
				}
				(v12).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ModifyOrder) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ModifyOrder) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ModifyOrder) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ModifyOrder) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx5(l, v)
}
func easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx6(in *jlexer.Lexer, out *ModifyArgs) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "instId":
			out.Instrument = string(in.String())
		case "ordId":
			out.OrderID = string(in.String())
		case "clOrdId":
			out.ClientOrderID = string(in.String())
		case "newPx":
			out.NewPrice = string(in.String())
		case "newSz":
			out.NewSize = string(in.String())
		case "reqId":
			out.RequestID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx6(out *jwriter.Writer, in ModifyArgs) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"instId\":"
		out.RawString(prefix[1:])
		out.String(string(in.Instrument))
	}
	if in.OrderID != "" {
		const prefix string = ",\"ordId\":"
		out.RawString(prefix)
		out.String(string(in.OrderID))
	}
	if in.ClientOrderID != "" {
		const prefix string = ",\"clOrdId\":"
		out.RawString(prefix)
		out.String(string(in.ClientOrderID))
	}
	{
		const prefix string = ",\"newPx\":"
		out.RawString(prefix)
		out.String(string(in.NewPrice))
	}
	{
		const prefix string = ",\"newSz\":"
		out.RawString(prefix)
		out.String(string(in.NewSize))
	}
	{
		const prefix string = ",\"reqId\":"
		out.RawString(prefix)
		out.String(string(in.RequestID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ModifyArgs) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ModifyArgs) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ModifyArgs) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ModifyArgs) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx6(l, v)
}
func easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx7(in *jlexer.Lexer, out *LoginMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "op":
			out.Op = EventType(in.String())
		case "args":
			if in.IsNull() {
				in.Skip()
				out.Args = nil
			} else {
				in.Delim('[')
				if out.Args == nil {
					if !in.IsDelim(']') {
						out.Args = make([]LoginArgs, 0, 1)
					} else {
						out.Args = []LoginArgs{}
					}
				} else {
					out.Args = (out.Args)[:0]
				}
				for !in.IsDelim(']') {
					var v13 LoginArgs
					(v13).UnmarshalEasyJSON(in)
					out.Args = append(out.Args, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx7(out *jwriter.Writer, in LoginMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"op\":"
		out.RawString(prefix[1:])
		out.String(string(in.Op))
	}
	{
		const prefix string = ",\"args\":"
		out.RawString(prefix)
		if in.Args == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.Args {
				if v14 > 0 {
					out.RawByte(',')
				}
				(v15).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LoginMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LoginMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LoginMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LoginMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx7(l, v)
}
func easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx8(in *jlexer.Lexer, out *LoginArgs) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "apiKey":
			out.APIKey = string(in.String())
		case "passphrase":
			out.Passphrase = string(in.String())
		case "timestamp":
			out.Timestamp = int64(in.Int64())
		case "sign":
			out.Sign = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx8(out *jwriter.Writer, in LoginArgs) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"apiKey\":"
		out.RawString(prefix[1:])
		out.String(string(in.APIKey))
	}
	{
		const prefix string = ",\"passphrase\":"
		out.RawString(prefix)
		out.String(string(in.Passphrase))
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.Int64(int64(in.Timestamp))
	}
	{
		const prefix string = ",\"sign\":"
		out.RawString(prefix)
		out.String(string(in.Sign))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LoginArgs) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LoginArgs) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LoginArgs) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LoginArgs) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx8(l, v)
}
func easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx9(in *jlexer.Lexer, out *Data) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "clOrdId":
			out.ClOrdID = string(in.String())
		case "ordId":
			out.OrdID = string(in.String())
		case "tag":
			out.Tag = string(in.String())
		case "reqId":
			out.ReqID = string(in.String())
		case "sCode":
			out.SCode = string(in.String())
		case "sMsg":
			out.SMsg = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx9(out *jwriter.Writer, in Data) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"clOrdId\":"
		out.RawString(prefix[1:])
		out.String(string(in.ClOrdID))
	}
	{
		const prefix string = ",\"ordId\":"
		out.RawString(prefix)
		out.String(string(in.OrdID))
	}
	{
		const prefix string = ",\"tag\":"
		out.RawString(prefix)
		out.String(string(in.Tag))
	}
	{
		const prefix string = ",\"reqId\":"
		out.RawString(prefix)
		out.String(string(in.ReqID))
	}
	{
		const prefix string = ",\"sCode\":"
		out.RawString(prefix)
		out.String(string(in.SCode))
	}
	{
		const prefix string = ",\"sMsg\":"
		out.RawString(prefix)
		out.String(string(in.SMsg))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Data) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Data) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Data) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Data) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx9(l, v)
}
func easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx10(in *jlexer.Lexer, out *CreateOrderArgs) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "instId":
			out.Instrument = string(in.String())
		case "clOrdId":
			out.ClientOrderID = string(in.String())
		case "side":
			out.Side = string(in.String())
		case "ordType":
			out.Type = string(in.String())
		case "sz":
			out.Quantity = string(in.String())
		case "px":
			out.Price = string(in.String())
		case "tdMode":
			out.TdMode = string(in.String())
		case "tgtCcy":
			out.TargetCurrency = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx10(out *jwriter.Writer, in CreateOrderArgs) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"instId\":"
		out.RawString(prefix[1:])
		out.String(string(in.Instrument))
	}
	{
		const prefix string = ",\"clOrdId\":"
		out.RawString(prefix)
		out.String(string(in.ClientOrderID))
	}
	{
		const prefix string = ",\"side\":"
		out.RawString(prefix)
		out.String(string(in.Side))
	}
	{
		const prefix string = ",\"ordType\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"sz\":"
		out.RawString(prefix)
		out.String(string(in.Quantity))
	}
	if in.Price != "" {
		const prefix string = ",\"px\":"
		out.RawString(prefix)
		out.String(string(in.Price))
	}
	{
		const prefix string = ",\"tdMode\":"
		out.RawString(prefix)
		out.String(string(in.TdMode))
	}
	if in.TargetCurrency != "" {
		const prefix string = ",\"tgtCcy\":"
		out.RawString(prefix)
		out.String(string(in.TargetCurrency))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateOrderArgs) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateOrderArgs) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateOrderArgs) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateOrderArgs) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx10(l, v)
}
func easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx11(in *jlexer.Lexer, out *CreateOrder) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "op":
			out.Op = EventType(in.String())
		case "args":
			if in.IsNull() {
				in.Skip()
				out.Args = nil
			} else {
				in.Delim('[')
				if out.Args == nil {
					if !in.IsDelim(']') {
						out.Args = make([]CreateOrderArgs, 0, 0)
					} else {
						out.Args = []CreateOrderArgs{}
					}
				} else {
					out.Args = (out.Args)[:0]
				}
				for !in.IsDelim(']') {
					var v16 CreateOrderArgs
					(v16).UnmarshalEasyJSON(in)
					out.Args = append(out.Args, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx11(out *jwriter.Writer, in CreateOrder) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"op\":"
		out.RawString(prefix)
		out.String(string(in.Op))
	}
	{
		const prefix string = ",\"args\":"
		out.RawString(prefix)
		if in.Args == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v17, v18 := range in.Args {
				if v17 > 0 {
					out.RawByte(',')
				}
				(v18).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateOrder) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateOrder) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateOrder) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateOrder) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx11(l, v)
}
func easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx12(in *jlexer.Lexer, out *CancelOrder) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "op":
			out.Op = EventType(in.String())
		case "args":
			if in.IsNull() {
				in.Skip()
				out.Args = nil
			} else {
				in.Delim('[')
				if out.Args == nil {
					if !in.IsDelim(']') {
						out.Args = make([]CancelArgs, 0, 1)
					} else {
						out.Args = []CancelArgs{}
					}
				} else {
					out.Args = (out.Args)[:0]
				}
				for !in.IsDelim(']') {
					var v19 CancelArgs
					(v19).UnmarshalEasyJSON(in)
					out.Args = append(out.Args, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx12(out *jwriter.Writer, in CancelOrder) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"op\":"
		out.RawString(prefix)
		out.String(string(in.Op))
	}
	{
		const prefix string = ",\"args\":"
		out.RawString(prefix)
		if in.Args == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.Args {
				if v20 > 0 {
					out.RawByte(',')
				}
				(v21).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CancelOrder) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CancelOrder) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CancelOrder) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CancelOrder) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx12(l, v)
}
func easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx13(in *jlexer.Lexer, out *CancelArgs) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "instId":
			out.InstID = string(in.String())
		case "clOrdId":
			out.ClOrdID = string(in.String())
		case "ordId":
			out.OrdID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx13(out *jwriter.Writer, in CancelArgs) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"instId\":"
		out.RawString(prefix[1:])
		out.String(string(in.InstID))
	}
	if in.ClOrdID != "" {
		const prefix string = ",\"clOrdId\":"
		out.RawString(prefix)
		out.String(string(in.ClOrdID))
	}
	if in.OrdID != "" {
		const prefix string = ",\"ordId\":"
		out.RawString(prefix)
		out.String(string(in.OrdID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CancelArgs) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CancelArgs) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9d6b4be7EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CancelArgs) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CancelArgs) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9d6b4be7DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesOkx13(l, v)
}
