// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package gateio

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE0009855DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio(in *jlexer.Lexer, out *OrderBookUpdate) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "time":
			out.Time = int64(in.Int64())
		case "time_ms":
			out.TimeMS = int64(in.Int64())
		case "channel":
			out.Channel = string(in.String())
		case "event":
			out.Event = EventType(in.String())
		case "result":
			(out.Result).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE0009855EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio(out *jwriter.Writer, in OrderBookUpdate) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Time))
	}
	{
		const prefix string = ",\"time_ms\":"
		out.RawString(prefix)
		out.Int64(int64(in.TimeMS))
	}
	{
		const prefix string = ",\"channel\":"
		out.RawString(prefix)
		out.String(string(in.Channel))
	}
	{
		const prefix string = ",\"event\":"
		out.RawString(prefix)
		out.String(string(in.Event))
	}
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix)
		(in.Result).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OrderBookUpdate) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE0009855EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OrderBookUpdate) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE0009855EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OrderBookUpdate) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE0009855DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OrderBookUpdate) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE0009855DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio(l, v)
}
func easyjsonE0009855DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio1(in *jlexer.Lexer, out *OrderBookResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "t":
			out.TimeMS = int64(in.Int64())
		case "lastUpdateId":
			out.LastUpdateID = int64(in.Int64())
		case "s":
			out.S = string(in.String())
		case "bids":
			if in.IsNull() {
				in.Skip()
				out.Bids = nil
			} else {
				in.Delim('[')
				if out.Bids == nil {
					if !in.IsDelim(']') {
						out.Bids = make([][]string, 0, 2)
					} else {
						out.Bids = [][]string{}
					}
				} else {
					out.Bids = (out.Bids)[:0]
				}
				for !in.IsDelim(']') {
					var v1 []string
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						in.Delim('[')
						if v1 == nil {
							if !in.IsDelim(']') {
								v1 = make([]string, 0, 4)
							} else {
								v1 = []string{}
							}
						} else {
							v1 = (v1)[:0]
						}
						for !in.IsDelim(']') {
							var v2 string
							v2 = string(in.String())
							v1 = append(v1, v2)
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Bids = append(out.Bids, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "asks":
			if in.IsNull() {
				in.Skip()
				out.Asks = nil
			} else {
				in.Delim('[')
				if out.Asks == nil {
					if !in.IsDelim(']') {
						out.Asks = make([][]string, 0, 2)
					} else {
						out.Asks = [][]string{}
					}
				} else {
					out.Asks = (out.Asks)[:0]
				}
				for !in.IsDelim(']') {
					var v3 []string
					if in.IsNull() {
						in.Skip()
						v3 = nil
					} else {
						in.Delim('[')
						if v3 == nil {
							if !in.IsDelim(']') {
								v3 = make([]string, 0, 4)
							} else {
								v3 = []string{}
							}
						} else {
							v3 = (v3)[:0]
						}
						for !in.IsDelim(']') {
							var v4 string
							v4 = string(in.String())
							v3 = append(v3, v4)
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Asks = append(out.Asks, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE0009855EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio1(out *jwriter.Writer, in OrderBookResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"t\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.TimeMS))
	}
	{
		const prefix string = ",\"lastUpdateId\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastUpdateID))
	}
	{
		const prefix string = ",\"s\":"
		out.RawString(prefix)
		out.String(string(in.S))
	}
	{
		const prefix string = ",\"bids\":"
		out.RawString(prefix)
		if in.Bids == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Bids {
				if v5 > 0 {
					out.RawByte(',')
				}
				if v6 == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v7, v8 := range v6 {
						if v7 > 0 {
							out.RawByte(',')
						}
						out.String(string(v8))
					}
					out.RawByte(']')
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"asks\":"
		out.RawString(prefix)
		if in.Asks == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.Asks {
				if v9 > 0 {
					out.RawByte(',')
				}
				if v10 == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v11, v12 := range v10 {
						if v11 > 0 {
							out.RawByte(',')
						}
						out.String(string(v12))
					}
					out.RawByte(']')
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OrderBookResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE0009855EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OrderBookResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE0009855EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OrderBookResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE0009855DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OrderBookResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE0009855DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio1(l, v)
}
func easyjsonE0009855DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio2(in *jlexer.Lexer, out *MDRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "time":
			out.Time = int64(in.Int64())
		case "channel":
			out.Channel = string(in.String())
		case "event":
			out.Event = EventType(in.String())
		case "payload":
			if in.IsNull() {
				in.Skip()
				out.Payload = nil
			} else {
				in.Delim('[')
				if out.Payload == nil {
					if !in.IsDelim(']') {
						out.Payload = make([][3]string, 0, 1)
					} else {
						out.Payload = [][3]string{}
					}
				} else {
					out.Payload = (out.Payload)[:0]
				}
				for !in.IsDelim(']') {
					var v13 [3]string
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('[')
						v14 := 0
						for !in.IsDelim(']') {
							if v14 < 3 {
								(v13)[v14] = string(in.String())
								v14++
							} else {
								in.SkipRecursive()
							}
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Payload = append(out.Payload, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE0009855EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio2(out *jwriter.Writer, in MDRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Time))
	}
	{
		const prefix string = ",\"channel\":"
		out.RawString(prefix)
		out.String(string(in.Channel))
	}
	{
		const prefix string = ",\"event\":"
		out.RawString(prefix)
		out.String(string(in.Event))
	}
	{
		const prefix string = ",\"payload\":"
		out.RawString(prefix)
		if in.Payload == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v15, v16 := range in.Payload {
				if v15 > 0 {
					out.RawByte(',')
				}
				out.RawByte('[')
				for v17 := range v16 {
					if v17 > 0 {
						out.RawByte(',')
					}
					out.String(string((v16)[v17]))
				}
				out.RawByte(']')
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MDRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE0009855EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MDRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE0009855EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MDRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE0009855DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MDRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE0009855DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio2(l, v)
}
func easyjsonE0009855DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio3(in *jlexer.Lexer, out *CommonResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "time":
			out.Time = int64(in.Int64())
		case "time_ms":
			out.TimeMS = int64(in.Int64())
		case "channel":
			out.Channel = string(in.String())
		case "event":
			out.Event = string(in.String())
		case "error":
			easyjsonE0009855Decode(in, &out.Error)
		case "result":
			if m, ok := out.Result.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Result.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Result = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE0009855EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio3(out *jwriter.Writer, in CommonResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Time))
	}
	{
		const prefix string = ",\"time_ms\":"
		out.RawString(prefix)
		out.Int64(int64(in.TimeMS))
	}
	{
		const prefix string = ",\"channel\":"
		out.RawString(prefix)
		out.String(string(in.Channel))
	}
	{
		const prefix string = ",\"event\":"
		out.RawString(prefix)
		out.String(string(in.Event))
	}
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		easyjsonE0009855Encode(out, in.Error)
	}
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix)
		if m, ok := in.Result.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Result.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Result))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CommonResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE0009855EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CommonResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE0009855EncodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CommonResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE0009855DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CommonResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE0009855DecodeStudentgitKataAcademyQuantTorqueInternalAdaptersWebsocketClientsTypesGateio3(l, v)
}
func easyjsonE0009855Decode(in *jlexer.Lexer, out *struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "code":
			out.Code = int64(in.Int64())
		case "message":
			out.Message = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE0009855Encode(out *jwriter.Writer, in struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Code))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	out.RawByte('}')
}
